version: '2'

services:

  feat:
    build: .
    volumes:
      - '../:/app'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '3000:3000'

  mongo:
    image: mongo:3.0
    ports:
      - '27017:27017'
