version: '2'

services:

  app:
    build: .
    volumes:
      - '../:/app'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '${FEAT_APP_PORT}:3000'
    container_name: feat_app

  mongo:
    image: mongo:3.0
    ports:
      - '${FEAT_MONGO_PORT}:27017'
    container_name: feat_mongo
