version: '2'

services:

  app:
    build: app
    volumes:
      - ../../:/app
      - ../../../cache/repository:/cache/repository
      - ../../../cache/build:/cache/build
      - ../../../cache/proxyDomain:/cache/proxyDomain
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    container_name: feat_app

  mongo:
    image: mongo:3.0
    ports:
      - '${FEAT_MONGO_PORT}:27017'
    networks:
      - internal
    container_name: feat_mongo

  nginx:
    build: nginx
    volumes:
      - ../../../cache/proxyDomain:/etc/nginx/conf.d/proxyDomain
    ports:
      - '${FEAT_NGINX_PORT}:80'
    networks:
      - internal
      - build
    container_name: feat_nginx

networks:
  internal:
  build:

